api_platform:
    title: Hello API Platform
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src']
    defaults:
        stateless: true
        route_prefix: /api
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
